### ISSUE TITLE
You seem to be using a very old version of Lasagne

### ISSUE THREAD

**Issue by CBrauer** [SkidanovAlex/ShallowNeuralDecisionForest#3]
Hi,

1. Please, I beg of you, move to Python 3.6
2. I had to load the latest version of Lasagne `using:`
```
pip install --upgrade --no-deps https://github.com/Theano/Theano/archive/master.zip
pip install --upgrade --no-deps https://github.com/Lasagne/Lasagne/archive/master.zip
```
Your code no longer works with the latest version, Lasagne 0.2,
I get: "get_params() got an unexpected keyword argument 'unwrap_shared'" in method "_get_all_trainable_params".

 3. Please do not use "fetch_mldata".  This server is down. Instead use:
```
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/")
X = mnist.train.images.astype('float64')
y = mnist.train.labels
```
Thanks.
Charles
